version: '3.8'

services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap_data/certificates:/container/service/slapd/assets/certs
      - ./ldap_data/slapd/database:/var/lib/ldap
      - ./ldap_data/slapd/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION: example
      - LDAP_DOMAIN: example.com
      - LDAP_ADMIN_USERNAME: ${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
      - "LDAP_BASE_DN=dc=example,dc=com"
      - LDAP_TLS_CRT_FILENAME: server.crt
      - LDAP_TLS_KEY_FILENAME: server.key
      - LDAP_TLS_CA_CRT_FILENAME: example.com.ca.crt
      - LDAP_READONLY_USER: true
      - LDAP_READONLY_USER_USERNAME: ${LDAP_READONLY_USER_USERNAME}
      - LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_USER_PASSWORD}
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "80:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS: openldap
      - PHPLDAPADMIN_HTTPS: false
    depends_on:
      - openldap
    networks:
      - openldap

networks:
  openldap:
    driver: bridge
